background {
    monitor =
    path = ~/Imagens/wallpaper.jpg
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 3%
    outline_thickness = 1
    rounding = 5
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font

    position = -30, 0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 25
    font_family = $font

    position = -30, -150
    halign = right
    valign = top
}
